repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=500

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^.*\b(migrations)\b.*$

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python_venv
        types: [python]
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
      - id: tox
        name: tox
        entry: tox
        language: python
        types: [ python ]
